/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.ue.ui;

import java.awt.BorderLayout;

/**
 *
 * @author mxmol
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        Solicitar_prestamo p1 = new Solicitar_prestamo ();
        p1.setSize(800,500);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        separador5 = new javax.swing.JSeparator();
        separador6 = new javax.swing.JSeparator();
        solicitud_de_libro = new javax.swing.JButton();
        consulta_de_libro = new javax.swing.JButton();
        Registro_de_libro = new javax.swing.JButton();
        consulta_de_libro3 = new javax.swing.JButton();
        Registro_de_usuario = new javax.swing.JButton();
        buttoncerrarsesion = new javax.swing.JButton();
        negro_login2 = new javax.swing.JLabel();
        negro_login = new javax.swing.JLabel();
        naranja_login = new javax.swing.JLabel();
        naranja2_login = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separador1.setBackground(new java.awt.Color(244, 121, 32));
        separador1.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 210, 10));

        separador2.setBackground(new java.awt.Color(244, 121, 32));
        separador2.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 210, 10));

        separador3.setBackground(new java.awt.Color(244, 121, 32));
        separador3.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 210, 10));

        separador4.setBackground(new java.awt.Color(244, 121, 32));
        separador4.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 210, 10));

        separador5.setBackground(new java.awt.Color(244, 121, 32));
        separador5.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 210, 10));

        separador6.setBackground(new java.awt.Color(244, 121, 32));
        separador6.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 210, 10));

        solicitud_de_libro.setBackground(new java.awt.Color(51, 49, 50));
        solicitud_de_libro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        solicitud_de_libro.setForeground(new java.awt.Color(255, 255, 255));
        solicitud_de_libro.setText("SOLICITAR PRESTAMO");
        solicitud_de_libro.setBorder(null);
        solicitud_de_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitud_de_libroActionPerformed(evt);
            }
        });
        jPanel1.add(solicitud_de_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 210, 60));

        consulta_de_libro.setBackground(new java.awt.Color(51, 49, 50));
        consulta_de_libro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        consulta_de_libro.setForeground(new java.awt.Color(255, 255, 255));
        consulta_de_libro.setText("CONSULTA DE LIBRO");
        consulta_de_libro.setBorder(new javax.swing.border.MatteBorder(null));
        consulta_de_libro.setBorderPainted(false);
        consulta_de_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_de_libroActionPerformed(evt);
            }
        });
        jPanel1.add(consulta_de_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 210, 60));

        Registro_de_libro.setBackground(new java.awt.Color(51, 49, 50));
        Registro_de_libro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Registro_de_libro.setForeground(new java.awt.Color(255, 255, 255));
        Registro_de_libro.setText("REGISTRO DE LIBRO");
        Registro_de_libro.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Registro_de_libro.setBorderPainted(false);
        Registro_de_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registro_de_libroActionPerformed(evt);
            }
        });
        jPanel1.add(Registro_de_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 210, 60));

        consulta_de_libro3.setBackground(new java.awt.Color(51, 49, 50));
        consulta_de_libro3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        consulta_de_libro3.setForeground(new java.awt.Color(255, 255, 255));
        consulta_de_libro3.setText("DEVOLUCION");
        consulta_de_libro3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        consulta_de_libro3.setBorderPainted(false);
        consulta_de_libro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_de_libro3ActionPerformed(evt);
            }
        });
        jPanel1.add(consulta_de_libro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 210, 60));

        Registro_de_usuario.setBackground(new java.awt.Color(51, 49, 50));
        Registro_de_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Registro_de_usuario.setForeground(new java.awt.Color(255, 255, 255));
        Registro_de_usuario.setText("REGISTRAR USUARIO");
        Registro_de_usuario.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        Registro_de_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registro_de_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Registro_de_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 210, 60));

        buttoncerrarsesion.setBackground(new java.awt.Color(51, 49, 50));
        buttoncerrarsesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttoncerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        buttoncerrarsesion.setText("Cerrar sesion");
        buttoncerrarsesion.setBorder(null);
        buttoncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncerrarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(buttoncerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 160, 50));

        negro_login2.setBackground(new java.awt.Color(51, 49, 50));
        negro_login2.setOpaque(true);
        jPanel1.add(negro_login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 20, 520));

        negro_login.setBackground(new java.awt.Color(51, 49, 50));
        negro_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        negro_login.setOpaque(true);
        jPanel1.add(negro_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 210, 520));

        naranja_login.setBackground(new java.awt.Color(251, 165, 26));
        naranja_login.setOpaque(true);
        jPanel1.add(naranja_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 220, 520));

        naranja2_login.setBackground(new java.awt.Color(244, 121, 32));
        naranja2_login.setOpaque(true);
        jPanel1.add(naranja2_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 230, 520));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 570, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncerrarsesionActionPerformed

        Principal v1 =new Principal();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttoncerrarsesionActionPerformed

    private void solicitud_de_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitud_de_libroActionPerformed
        Solicitar_prestamo p1 = new Solicitar_prestamo ();
        p1.setSize(800,500);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_solicitud_de_libroActionPerformed

    private void consulta_de_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_de_libroActionPerformed
        Consultar_libro p2 = new Consultar_libro ();
        p2.setSize(800,500);
        p2.setLocation(0,0);
        
        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_consulta_de_libroActionPerformed

    private void Registro_de_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registro_de_libroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registro_de_libroActionPerformed

    private void Registro_de_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registro_de_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registro_de_usuarioActionPerformed

    private void consulta_de_libro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_de_libro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consulta_de_libro3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registro_de_libro;
    private javax.swing.JButton Registro_de_usuario;
    private javax.swing.JButton buttoncerrarsesion;
    private javax.swing.JButton consulta_de_libro;
    private javax.swing.JButton consulta_de_libro3;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel naranja2_login;
    private javax.swing.JLabel naranja_login;
    private javax.swing.JLabel negro_login;
    private javax.swing.JLabel negro_login2;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JSeparator separador6;
    private javax.swing.JButton solicitud_de_libro;
    // End of variables declaration//GEN-END:variables
}
