/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.ue.ui;

import java.awt.BorderLayout;

/**
 *
 * @author mxmol
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        Solicitar_prestamo p1 = new Solicitar_prestamo ();
        p1.setSize(800,500);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        negro_login2 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        menubarra = new javax.swing.JPanel();
        solicitud_de_libro = new javax.swing.JButton();
        consulta_de_libro = new javax.swing.JButton();
        negro_login1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        negro_login2.setBackground(new java.awt.Color(51, 49, 50));
        negro_login2.setOpaque(true);
        jPanel1.add(negro_login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 20, 520));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 520));

        solicitud_de_libro.setBackground(new java.awt.Color(51, 49, 50));
        solicitud_de_libro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        solicitud_de_libro.setForeground(new java.awt.Color(255, 255, 255));
        solicitud_de_libro.setText("SOLICITAR PRESTAMO");
        solicitud_de_libro.setBorder(null);
        solicitud_de_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitud_de_libroActionPerformed(evt);
            }
        });

        consulta_de_libro.setBackground(new java.awt.Color(51, 49, 50));
        consulta_de_libro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        consulta_de_libro.setForeground(new java.awt.Color(255, 255, 255));
        consulta_de_libro.setText("CONSULTA DE LIBRO");
        consulta_de_libro.setBorder(new javax.swing.border.MatteBorder(null));
        consulta_de_libro.setBorderPainted(false);
        consulta_de_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_de_libroActionPerformed(evt);
            }
        });

        negro_login1.setBackground(new java.awt.Color(51, 49, 50));
        negro_login1.setOpaque(true);

        javax.swing.GroupLayout menubarraLayout = new javax.swing.GroupLayout(menubarra);
        menubarra.setLayout(menubarraLayout);
        menubarraLayout.setHorizontalGroup(
            menubarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarraLayout.createSequentialGroup()
                .addComponent(negro_login1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consulta_de_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solicitud_de_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menubarraLayout.setVerticalGroup(
            menubarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubarraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menubarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(negro_login1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menubarraLayout.createSequentialGroup()
                        .addComponent(solicitud_de_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(consulta_de_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(202, 202, 202))
        );

        jPanel1.add(menubarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 230, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solicitud_de_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitud_de_libroActionPerformed
        Solicitar_prestamo p1 = new Solicitar_prestamo ();
        p1.setSize(800,500);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_solicitud_de_libroActionPerformed

    private void consulta_de_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_de_libroActionPerformed
        Consultar_libro p2 = new Consultar_libro ();
        p2.setSize(800,500);
        p2.setLocation(0,0);
        
        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_consulta_de_libroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulta_de_libro;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menubarra;
    private javax.swing.JLabel negro_login1;
    private javax.swing.JLabel negro_login2;
    private javax.swing.JButton solicitud_de_libro;
    // End of variables declaration//GEN-END:variables
}
