/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.ue.ui;

/**
 *
 * @author mxmol
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        negro_login = new javax.swing.JLabel();
        negro_login1 = new javax.swing.JLabel();
        naranja_login = new javax.swing.JLabel();
        naranja_login1 = new javax.swing.JLabel();
        naranja2_login = new javax.swing.JLabel();
        naranja2_login1 = new javax.swing.JLabel();
        Registro_de_usuario = new javax.swing.JLabel();
        documento = new javax.swing.JLabel();
        textdocumento = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        nombre = new javax.swing.JLabel();
        textnombre = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        apellido = new javax.swing.JLabel();
        textapellido = new javax.swing.JTextField();
        separador3 = new javax.swing.JSeparator();
        telefono = new javax.swing.JLabel();
        texttelefono = new javax.swing.JTextField();
        separador4 = new javax.swing.JSeparator();
        correo = new javax.swing.JLabel();
        textcorreo = new javax.swing.JTextField();
        separador6 = new javax.swing.JSeparator();
        inicio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        negro_login.setBackground(new java.awt.Color(51, 49, 50));
        negro_login.setOpaque(true);
        jPanel1.add(negro_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 70));

        negro_login1.setBackground(new java.awt.Color(51, 49, 50));
        negro_login1.setOpaque(true);
        jPanel1.add(negro_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 80, 500));

        naranja_login.setBackground(new java.awt.Color(251, 165, 26));
        naranja_login.setOpaque(true);
        jPanel1.add(naranja_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 100, 520));

        naranja_login1.setBackground(new java.awt.Color(251, 165, 26));
        naranja_login1.setOpaque(true);
        jPanel1.add(naranja_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        naranja2_login.setBackground(new java.awt.Color(244, 121, 32));
        naranja2_login.setOpaque(true);
        jPanel1.add(naranja2_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 520));

        naranja2_login1.setBackground(new java.awt.Color(244, 121, 32));
        naranja2_login1.setOpaque(true);
        jPanel1.add(naranja2_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 810, 50));

        Registro_de_usuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Registro_de_usuario.setText("REGISTRO USUARIO ");
        jPanel1.add(Registro_de_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        documento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        documento.setText("DOCUMENTO");
        documento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        documento.setNextFocusableComponent(textdocumento);
        jPanel1.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 20));

        textdocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textdocumento.setForeground(new java.awt.Color(153, 153, 153));
        textdocumento.setText("Introduce documento de identificacion");
        textdocumento.setBorder(null);
        textdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(textdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 270, 20));

        separador1.setBackground(new java.awt.Color(244, 121, 32));
        separador1.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 10));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre.setText("NOMBRE");
        nombre.setNextFocusableComponent(textnombre);
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 20));

        textnombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textnombre.setForeground(new java.awt.Color(153, 153, 153));
        textnombre.setText("Introduce sus nombres");
        textnombre.setBorder(null);
        textnombre.setNextFocusableComponent(nombre);
        textnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnombreActionPerformed(evt);
            }
        });
        jPanel1.add(textnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 280, 20));

        separador2.setBackground(new java.awt.Color(244, 121, 32));
        separador2.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 280, 10));

        apellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        apellido.setText("APELLIDO");
        apellido.setNextFocusableComponent(textapellido);
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        textapellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textapellido.setForeground(new java.awt.Color(153, 153, 153));
        textapellido.setText("Introduce sus apellidos");
        textapellido.setToolTipText("");
        textapellido.setBorder(null);
        textapellido.setNextFocusableComponent(apellido);
        textapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textapellidoActionPerformed(evt);
            }
        });
        jPanel1.add(textapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, 20));

        separador3.setBackground(new java.awt.Color(244, 121, 32));
        separador3.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 280, 10));

        telefono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        telefono.setText("TELEFONO");
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 20));

        texttelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        texttelefono.setForeground(new java.awt.Color(153, 153, 153));
        texttelefono.setText("Introduce telefono de contacto");
        texttelefono.setBorder(null);
        texttelefono.setNextFocusableComponent(telefono);
        texttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(texttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 20));

        separador4.setBackground(new java.awt.Color(244, 121, 32));
        separador4.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 280, 10));

        correo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        correo.setText("CORREO");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        textcorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textcorreo.setForeground(new java.awt.Color(153, 153, 153));
        textcorreo.setText("Introduce correo de contacto");
        textcorreo.setBorder(null);
        textcorreo.setNextFocusableComponent(correo);
        textcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(textcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, 20));

        separador6.setBackground(new java.awt.Color(244, 121, 32));
        separador6.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 280, 10));

        inicio.setBackground(new java.awt.Color(251, 165, 26));
        inicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inicio.setText("VOLVER A INICIO");
        inicio.setBorder(null);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 140, 40));

        jButton1.setBackground(new java.awt.Color(251, 165, 26));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("BORRAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 140, 40));

        jButton2.setBackground(new java.awt.Color(251, 165, 26));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("REGISTRAR");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        Principal v1 =new Principal();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_inicioActionPerformed

    private void textnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnombreActionPerformed

    private void textapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textapellidoActionPerformed

    private void textdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdocumentoActionPerformed

    private void textcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcorreoActionPerformed

    private void texttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttelefonoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registro_de_usuario;
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel documento;
    private javax.swing.JButton inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel naranja2_login;
    private javax.swing.JLabel naranja2_login1;
    private javax.swing.JLabel naranja_login;
    private javax.swing.JLabel naranja_login1;
    private javax.swing.JLabel negro_login;
    private javax.swing.JLabel negro_login1;
    private javax.swing.JLabel nombre;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador6;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField textapellido;
    private javax.swing.JTextField textcorreo;
    private javax.swing.JTextField textdocumento;
    private javax.swing.JTextField textnombre;
    private javax.swing.JTextField texttelefono;
    // End of variables declaration//GEN-END:variables
}
