/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.ue.ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mxmol
 */
public class z3Re_Lector extends javax.swing.JPanel {

    /**
     * Creates new form z3Re_Lector
     */
    public z3Re_Lector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lect_nombre = new javax.swing.JLabel();
        textlect_nombre = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        lect_apellido = new javax.swing.JLabel();
        textlect_apellido = new javax.swing.JTextField();
        separador3 = new javax.swing.JSeparator();
        lect_direccion = new javax.swing.JLabel();
        textlect_direccion = new javax.swing.JTextField();
        separador4 = new javax.swing.JSeparator();
        lect_telefono = new javax.swing.JLabel();
        textlect_telefono = new javax.swing.JTextField();
        separador5 = new javax.swing.JSeparator();
        lect_documento = new javax.swing.JLabel();
        textlect_documento = new javax.swing.JTextField();
        separador6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(251, 165, 26));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 500));

        lect_nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_nombre.setText("NOMBRE ");
        jPanel1.add(lect_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, -1));

        textlect_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textlect_nombre.setForeground(new java.awt.Color(102, 102, 102));
        textlect_nombre.setText("Introduce nombre del usuario");
        textlect_nombre.setBorder(null);
        textlect_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlect_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(textlect_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 410, 30));

        separador2.setBackground(new java.awt.Color(244, 121, 32));
        separador2.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 410, 10));

        lect_apellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_apellido.setText("APELLIDO ");
        jPanel1.add(lect_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        textlect_apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textlect_apellido.setForeground(new java.awt.Color(102, 102, 102));
        textlect_apellido.setText("Introduce nombre del usuario");
        textlect_apellido.setBorder(null);
        textlect_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlect_apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(textlect_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 410, 30));

        separador3.setBackground(new java.awt.Color(244, 121, 32));
        separador3.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 410, 10));

        lect_direccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_direccion.setText("DIRECCION");
        jPanel1.add(lect_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 160, -1));

        textlect_direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textlect_direccion.setForeground(new java.awt.Color(102, 102, 102));
        textlect_direccion.setText("Introduce nombre del usuario");
        textlect_direccion.setBorder(null);
        textlect_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlect_direccionActionPerformed(evt);
            }
        });
        jPanel1.add(textlect_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 410, 30));

        separador4.setBackground(new java.awt.Color(244, 121, 32));
        separador4.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 410, 10));

        lect_telefono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_telefono.setText("TELEFONO");
        jPanel1.add(lect_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 160, -1));

        textlect_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textlect_telefono.setForeground(new java.awt.Color(102, 102, 102));
        textlect_telefono.setText("Introduce nombre del usuario");
        textlect_telefono.setBorder(null);
        textlect_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlect_telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(textlect_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 410, 30));

        separador5.setBackground(new java.awt.Color(244, 121, 32));
        separador5.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 410, 10));

        lect_documento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_documento.setText("DOCUMENTO");
        jPanel1.add(lect_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 160, -1));

        textlect_documento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textlect_documento.setForeground(new java.awt.Color(102, 102, 102));
        textlect_documento.setText("Introduce nombre del usuario");
        textlect_documento.setBorder(null);
        textlect_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlect_documentoActionPerformed(evt);
            }
        });
        jPanel1.add(textlect_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 410, 30));

        separador6.setBackground(new java.awt.Color(244, 121, 32));
        separador6.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 410, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 130, -1));

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                       
        Usuarios usuario = new Usuarios(textnombre.getText(), textapellido.getText(), 
        textcorreo.getText(), textcontraseña.getText(), textdocumento.getText(), texttelefono.getText() );
        
        UsuariosDao dao = new UsuariosDao();
        try {
            dao.addUser(usuario);
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        cleanFields();
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textlect_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlect_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlect_documentoActionPerformed

    private void textlect_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlect_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlect_telefonoActionPerformed

    private void textlect_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlect_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlect_direccionActionPerformed

    private void textlect_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlect_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlect_apellidoActionPerformed

    private void textlect_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlect_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlect_nombreActionPerformed

        private void cleanFields(){
        textdocumento.setText("");
        textnombre.setText("");
        textapellido.setText("");
        textcorreo.setText("");
        textcontraseña.setText("");
        texttelefono.setText("");
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lect_apellido;
    private javax.swing.JLabel lect_direccion;
    private javax.swing.JLabel lect_documento;
    private javax.swing.JLabel lect_nombre;
    private javax.swing.JLabel lect_telefono;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JSeparator separador6;
    private javax.swing.JTextField textlect_apellido;
    private javax.swing.JTextField textlect_direccion;
    private javax.swing.JTextField textlect_documento;
    private javax.swing.JTextField textlect_nombre;
    private javax.swing.JTextField textlect_telefono;
    // End of variables declaration//GEN-END:variables
}
