/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.ue.ui;

import co.edu.ue.dao.LectoresDao;
import co.edu.ue.entidades.Lectores;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mxmol
 */
public class z3Re_Lector extends javax.swing.JPanel {

    /**
     * Creates new form z3Re_Lector
     */
    public z3Re_Lector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lect_nombre = new javax.swing.JLabel();
        txtEmailLector = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        lect_apellido = new javax.swing.JLabel();
        txtApellidoLector = new javax.swing.JTextField();
        separador3 = new javax.swing.JSeparator();
        lect_direccion = new javax.swing.JLabel();
        txtDireccionLector = new javax.swing.JTextField();
        separador4 = new javax.swing.JSeparator();
        lect_telefono = new javax.swing.JLabel();
        txtTelefonoLector = new javax.swing.JTextField();
        separador5 = new javax.swing.JSeparator();
        lect_documento = new javax.swing.JLabel();
        txtDocumentoLector = new javax.swing.JTextField();
        separador6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtNombreLector = new javax.swing.JTextField();
        lect_documento1 = new javax.swing.JLabel();
        separador7 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(251, 165, 26));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 500));

        lect_nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_nombre.setText("NOMBRE ");
        jPanel1.add(lect_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 160, -1));

        txtEmailLector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmailLector.setForeground(new java.awt.Color(102, 102, 102));
        txtEmailLector.setText("Introduce email lector");
        txtEmailLector.setBorder(null);
        txtEmailLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailLectorActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 410, 30));

        separador2.setBackground(new java.awt.Color(244, 121, 32));
        separador2.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 410, 10));

        lect_apellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_apellido.setText("APELLIDO ");
        jPanel1.add(lect_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 160, -1));

        txtApellidoLector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApellidoLector.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoLector.setText("Introduce apellido del lector");
        txtApellidoLector.setBorder(null);
        txtApellidoLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoLectorActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 410, 30));

        separador3.setBackground(new java.awt.Color(244, 121, 32));
        separador3.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 410, 10));

        lect_direccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_direccion.setText("DIRECCIÓN");
        jPanel1.add(lect_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, -1));

        txtDireccionLector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDireccionLector.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccionLector.setText("Introduce la direccion del lector");
        txtDireccionLector.setBorder(null);
        txtDireccionLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionLectorActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccionLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 410, 30));

        separador4.setBackground(new java.awt.Color(244, 121, 32));
        separador4.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 410, 10));

        lect_telefono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_telefono.setText("TELEFONO");
        jPanel1.add(lect_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, -1));

        txtTelefonoLector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefonoLector.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefonoLector.setText("Introduce telefono del lector");
        txtTelefonoLector.setBorder(null);
        txtTelefonoLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoLectorActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefonoLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 410, 30));

        separador5.setBackground(new java.awt.Color(244, 121, 32));
        separador5.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 410, 10));

        lect_documento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_documento.setText("EMAIL");
        jPanel1.add(lect_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 160, -1));

        txtDocumentoLector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDocumentoLector.setForeground(new java.awt.Color(102, 102, 102));
        txtDocumentoLector.setText("Introduce documento del lector");
        txtDocumentoLector.setBorder(null);
        txtDocumentoLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoLectorActionPerformed(evt);
            }
        });
        jPanel1.add(txtDocumentoLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 410, 30));

        separador6.setBackground(new java.awt.Color(244, 121, 32));
        separador6.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 410, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        txtNombreLector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreLector.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreLector.setText("Introduce nombre del lector");
        txtNombreLector.setBorder(null);
        txtNombreLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreLectorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 410, 30));

        lect_documento1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_documento1.setText("DOCUMENTO");
        jPanel1.add(lect_documento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, -1));

        separador7.setBackground(new java.awt.Color(244, 121, 32));
        separador7.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 410, 10));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("GUARDAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 130, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
                     

    private void btnRegistrarLectorActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                       
        Lectores lector = new Lectores(txtNombreLector.getText(), txtApellidoLector.getText(), 
        txtDireccionLector.getText(), txtTelefonoLector.getText(), txtDocumentoLector.getText(), txtEmailLector.getText() );
        
        LectoresDao dao = new LectoresDao();
        try {
            dao.addUser(lector);
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        cleanFields();    
    }
        
    private void textlect_apellidoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 


    private void textlect_direccionActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void textlect_telefonoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 
    // TODO add your handling code here:

    private void textlect_documentoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void txtDocumentoLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoLectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoLectorActionPerformed

    private void txtTelefonoLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoLectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoLectorActionPerformed

    private void txtDireccionLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionLectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionLectorActionPerformed

    private void txtApellidoLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoLectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoLectorActionPerformed

    private void txtEmailLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailLectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailLectorActionPerformed

    private void txtNombreLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreLectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLectorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

        private void cleanFields(){
        txtNombreLector.setText("");
        txtApellidoLector.setText("");
        txtDireccionLector.setText("");
        txtTelefonoLector.setText("");
        txtDocumentoLector.setText("");
        txtEmailLector.setText("");
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lect_apellido;
    private javax.swing.JLabel lect_direccion;
    private javax.swing.JLabel lect_documento;
    private javax.swing.JLabel lect_documento1;
    private javax.swing.JLabel lect_nombre;
    private javax.swing.JLabel lect_telefono;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JSeparator separador6;
    private javax.swing.JSeparator separador7;
    private javax.swing.JTextField txtApellidoLector;
    private javax.swing.JTextField txtDireccionLector;
    private javax.swing.JTextField txtDocumentoLector;
    private javax.swing.JTextField txtEmailLector;
    private javax.swing.JTextField txtNombreLector;
    private javax.swing.JTextField txtTelefonoLector;
    // End of variables declaration//GEN-END:variables
}
