/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.ue.ui;


import co.edu.ue.dao.AutoresDao;
import co.edu.ue.entidades.Autores;
import co.edu.ue.entidades.Editoriales;
import co.edu.ue.util.ModeloEditorial;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mxmol
 */
public class z4Re_Libro extends javax.swing.JPanel {

    /**
     * Creates new form z3Re_Lector
     */
    public z4Re_Libro() {
        initComponents();
        llenarEditorial();
    }
    
        private void llenarEditorial() {
    ModeloEditorial modEditorial = new ModeloEditorial();
    ArrayList<Editoriales> listaEditoriales = modEditorial.getEditoriales();
    cbxlector.removeAllItems();

    System.out.println("Cantidad de lectores obtenidos: " + listaEditoriales.size());

    for (int i = 0; i < listaEditoriales.size(); i++) {
        cbxlector.addItem(listaEditoriales.get(i).getEdit_nombre());
    }
    
    System.out.println("Cantidad de elementos en el JComboBox: " + cbxlector.getItemCount());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lect_id = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        lect_nombre = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbxlector = new javax.swing.JComboBox<>();

        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(251, 165, 26));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 500));

        lect_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_id.setText("TITULO DEL LIBRO");
        lect_id.setPreferredSize(new java.awt.Dimension(85, 22));
        jPanel1.add(lect_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 220, -1));

        txtTituloLibro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTituloLibro.setForeground(new java.awt.Color(102, 102, 102));
        txtTituloLibro.setText("Introduce el titulo libro");
        txtTituloLibro.setBorder(null);
        txtTituloLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloLibroActionPerformed(evt);
            }
        });
        jPanel1.add(txtTituloLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 410, 30));

        separador1.setBackground(new java.awt.Color(244, 121, 32));
        separador1.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 410, 10));

        lect_nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_nombre.setText("ID_EDITORIALES");
        jPanel1.add(lect_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, -1));

        separador2.setBackground(new java.awt.Color(244, 121, 32));
        separador2.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 410, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("GUARDAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 130, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 130, -1));

        cbxlector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxlector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxlectorActionPerformed(evt);
            }
        });
        jPanel1.add(cbxlector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 410, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLibroActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxlectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxlectorActionPerformed

    
    }//GEN-LAST:event_cbxlectorActionPerformed
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxlector;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lect_id;
    private javax.swing.JLabel lect_nombre;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
