/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.ue.ui;


import co.edu.ue.dao.AutoresDao;
import co.edu.ue.entidades.Autores;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mxmol
 */
public class z4Re_Libro extends javax.swing.JPanel {

    /**
     * Creates new form z3Re_Lector
     */
    public z4Re_Libro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lect_id = new javax.swing.JLabel();
        txtNombreAutor = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        lect_nombre = new javax.swing.JLabel();
        txtApellidoAutor = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnLimpiarAutor = new javax.swing.JButton();
        btnRegistrarAutor = new javax.swing.JButton();

        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(251, 165, 26));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 500));

        lect_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_id.setText("NOMBRE DEL AUTOR");
        jPanel1.add(lect_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 220, -1));

        txtNombreAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreAutor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreAutor.setText("Introduce el nombre del autor");
        txtNombreAutor.setBorder(null);
        txtNombreAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAutorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 410, 30));

        separador1.setBackground(new java.awt.Color(244, 121, 32));
        separador1.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 410, 10));

        lect_nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lect_nombre.setText("APELLIDO DEL AUTOR");
        jPanel1.add(lect_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 220, -1));

        txtApellidoAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApellidoAutor.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoAutor.setText("Introduce el apellido del autor");
        txtApellidoAutor.setBorder(null);
        txtApellidoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoAutorActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 410, 30));

        separador2.setBackground(new java.awt.Color(244, 121, 32));
        separador2.setForeground(new java.awt.Color(244, 121, 32));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 410, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        btnLimpiarAutor.setText("LIMPIAR");
        btnLimpiarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 433, 130, 40));

        btnRegistrarAutor.setText("REGISTRAR");
        btnRegistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 433, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoAutorActionPerformed

    private void txtNombreAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAutorActionPerformed

    private void btnLimpiarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAutorActionPerformed
        cleanFields();  
    }//GEN-LAST:event_btnLimpiarAutorActionPerformed
    
    private void cleanFields(){
        txtNombreAutor.setText("");
        txtApellidoAutor.setText("");
    }
    
    private void btnRegistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAutorActionPerformed
        Autores autor = new Autores(txtNombreAutor.getText(), txtApellidoAutor.getText());
        
        AutoresDao dao = new AutoresDao();
        try {
            dao.addUser(autor);
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        cleanFields();  
    }//GEN-LAST:event_btnRegistrarAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarAutor;
    private javax.swing.JButton btnRegistrarAutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lect_id;
    private javax.swing.JLabel lect_nombre;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField txtApellidoAutor;
    private javax.swing.JTextField txtNombreAutor;
    // End of variables declaration//GEN-END:variables
}
